### PR TITLE
50: add NME support

### PR DESCRIPTION
**Pull request by eric-gilbertson**
- define NME struct in config.kzsu.php
   - move Print View link below header bar
   - append NME options to track type selector
   - enable appropriate fields for NME
   - make swapNames smarter

### CODE REVIEW

**Comment by RocketMan** [comment]
Thanks Eric!

In general, this is looking good.  A couple questions:

* Each nme config file entry has an 'args' parameter.  What is the intended effect of this param?  I am seeing a single field 'Name/ID' for all nme's, including LID.

* What is the expected public view of nme's?  There is a difference between the in-app view (nothing is displayed) and Print View (a set separator is displayed).  I could see a set separator, as a NME is a set break, but we would need to display only one set separator when multiple adjacent special tracks occur together.  Simple enough logic, but would need to be added.

Also, editing an nme track yields unexpected behaviour.

**Comment by eric-gilbertson** [comment]
hey jim,

thanks for the quick feedback.

#1 args tells the form how many inputs are 'required'. if 0 then JS autopopulates the one required field with the NME type as a filler so the the required fields check passes but still allow user to enter a n optional value, eg the LID ID from spotbox.

Will take a look at items 2 and 3.

**Comment by RocketMan** [comment]
Thanks Eric.

The only one that needs fixing is the nme edit, and even that can wait.  If you want, I can accept the PR as-is so we can put this in stage for review, and then follow up from there.  Let me know what you think.

**Comment by RocketMan** [comment]
Hello Eric,

I made some small changes as well as added a rudimentary nme edit so we can get this onto stage.

Ultimately, I would like to see a track edit that is like the Ajax-based track add.  That way, the DJ could change the type (for example, from manual to tag or nme), which the current edit does not support.

Also, I updated the code to use the new PlaylistEntry/PlaylistObserver abstraction.  This allows lambda functions to handle the different track types.  Being a jQuery user, I think you will like this approach.

Thank you again for the nme contributions!!

**Pull request merged**
