### PR TITLE
94: allow user edit of playlist entry spin times

### PR DESCRIPTION
**Pull request by eric-gilbertson**
- add timepicker to the NME edit form and populate with existing time
    - set timepicker min/max to the show bein/end times
    - pass the updated time to updateTrack via the entry.Created
    - update with new time if it is within the show time
    - add TODO to 'impl/Playlist.php to update IDs when NME time is changed on update

### CODE REVIEW

**Comment by RocketMan** [comment]
Thanks Eric.  I've had a look and have several questions/observations:

1. Why do we allow editing of the timestamp only on log entries?  Similarly, with the proposed #117, why not allow edit or move of spins, comments, etc, as well?  The log entries are the 'legal' ones; if they can be edited or moved, then why not everything?  As a DJ, I would find it confusing and maybe a bit annoying that I could edit the timestamp only for some entries in my playlist and not others.  The DJ should have full control over the playlist, and doing it for log entries only seems like an incomplete solution.

2. The time picker is not functional under Safari; it's just a plain text field that allows non-numeric values to be entered.

3. Edit will not allow save without a timestamp value, even if one was not there before.  It is possible that the DJ does not know.  If there was no timestamp before, edit should allow save without a timestamp.

4. Editing an entry allows you to change its timestamp value to something that is out of temporal sequence with the other tracks in the playlist.  Maybe in that case, we would automatically move the track to the appropriate place; this is related to #117, so let's defer this for the moment.

5. Editing a comment resets its timestamp to midnight.

Thanks again, Eric, and best wishes for the new year.

**Comment by eric-gilbertson** [comment]
hi jim,

i'm still not convinced that there is much of a need to allow time edits for all PL types, but since you feel strongly about it I will make the change in my and address the other issues you raise in my next push. a prerequisite for incorporation of the feature is the time/id reordering in the DB. when can you check this in?

hny,

eric

**Comment by eric-gilbertson** [comment]
issues 1,3 & 5 have been addressed with push commit 21d9611. one outstanding issue is that the list iss not ordered correctly when doing the following on a 'live' playlist:
   * set time for an existing item to end of show - note, item is correctly reordered
   * add a new track - note that the spin time is correct but it is listed AFTER the previous item

suggest updating the order logic to either prohibit the setting of future dates by clipping time to now or enhancing the sequence logic to correctly handle this case (preferred). if the first approach is taken the front end can be subsequently updated but it is important that the backend protect against  misordered entries independent of the FE logic.

**Comment by RocketMan** [comment]
Awesome, thanks Eric.  I've had a cursory run, and it looks good.

I will investigate the issue with adding the live track and make the appropriate changes.

**Comment by RocketMan** [comment]
I see this is effectively a two-parter:  engine and UI.  For the engine, the correct thing is for insertTrack to order the timestamp correctly on insert as it does for update.  I have committed the fix for that.

That leaves the UI.  Because of the ajax nature of the builder, it still shows in the wrong place until a reload of the page.  Maybe you have some thought on that already?

In the meantime, I have removed the restriction of not using 'seq' outside the engine by ensuring it is monotonic, so you can consult its value by the newly public method IPlaylist::getSeq.  At least this way, you can find out where an inserted/updated track went.  Perhaps you could include this value in the return json to javascript for the add track operation, so the client side code will know where in the list it should go.

**Comment by RocketMan** [comment]
Hello Eric, it occurred to me that the reordering query adversely affects subsequent references to lastInsertId.  There was one such reference in ui/Playlists.php that was affected.

To remove the dependency on lastInsertId, I have updated the code so that the id for the inserted row is returned by the APIs.  This is done in the case of insertTrackEntry via the id property in PlaylistEntry, or via an optional return parameter in the case of insertTrack.

No action is required on your part, except to be aware.  ui/Playlists.php has been updated accordingly.

**Comment by RocketMan** [comment]
Hello Eric, unless you have more changes pending, I am prepared to accept the PR as-is, and we can follow-up later with a UI solution for the live-entry reordering issue (either restriction on future-dated times during live entry or ajax re-ordering.)

Going live with the Safari time picker issue is also fine for now; we can follow up with a fix for that as well.

Please let me know what you want to do.  Thanks again for this contribution!

**Comment by RocketMan** [comment]
FYI, I just pushed 22d13bf which fixes the UI for live playlist entry ordering.  Please check to make sure it is working as expected.

Unless you have more commits, I am prepared to merge the PR, just let me know.

**Pull request merged**
