### PR TITLE
Ericg/43 afile default sort

### PR DESCRIPTION
**Pull request by eric-gilbertson**
fix case where a-file list was not sorted on page load for 'n' type user roles. don't know why git thinks there is a conflict with this but since it is a small change thought perhaps you could resolve it.

### CODE REVIEW

**Comment by RocketMan** [comment]
Fixed conflict and merged.

I noticed that if a user is not logged in (that is, the general public), we don't show anything to indicate there is a review, since we're suppressing the reviewer column.

One idea would be to bring that column back for those users, but show the DJ airname (analogous to the Recent Reviews page), and for station members, show the real name.

For now, if the user is logged out, I simply added back the legacy way of showing there is a review.  I'm not completely happy with that solution, but it is a stop-gap for now, so those users at least see something.

**Comment by eric-gilbertson** [comment]
yes, it would be nice to show the reviewer in all cases. it would be clearer though if the same name were shown in both cases in order to avoid confusion between real and db names. i know that public display of real names has been an issue in the past but i wonder if folks still feel that way, eg would the reviewers object to having their last name listed in the public view?

**Comment by eric-gilbertson** [comment]
thanks for taking care of the merge.

**Comment by RocketMan** [comment]
I just pushed a change to show the reviewer as the usual DJ airname, analogous with Recent Reviews and the album details page, and to make the column visible for all users.  Please check it out on stage and let me know.

The only downside that I can see is that the DJ airname column now takes up potentially more real estate on screen.  However, usage of the airname is consistent everywhere, and we have restored the column for public users.

**Pull request merged**
