### PR TITLE
Ericg/166 play track

### PR DESCRIPTION
**Pull request by eric-gilbertson**
Add ability to associate a URL with a track so that the track can be played by clicking on the link from the track review page. Also add a URL entry field in the library editor's track entry table. Changes include:

   - add URL column to tracknames & colltracknames tables
   - add DB upgrade scripts
   - add URL field to track entry table in library editor
   - change track link review page to use new URL as its href and don't make it an anchor is no URL is provided
   - change Search -> Search Albums/Labels (to help distinguish the two modes used in this view)
  - move action buttons out of the track list table
   - remove some of the duplicate code
   - use single quote in HTML 
   - remove noTables option
   - use regex to identify track<DIGIT> element names

Test Cases:
Check the following for collection and non-collection disks and confirm that the review page is correct
   - add new disk and add tracks with and without URLS
   - edit disk and add tracks with and without URLS
   - confirm operation of action buttons, eg Add Track, More Tracks....

### CODE REVIEW

**Comment by RocketMan** [comment]
Thanks Eric!

>     * change track link review page to use new URL as its href and don't make it an anchor is no URL is provided

I am wondering if a little circle 'play' icon next to the track might be a better visual cue than a hyperlink?  Hyperlink in this context almost seems to me to be mystery meat navigation, while circle play is ubiquitous on the interwebs.  Can you make that change?

Also, do you think it would make sense to have an album-level play option as well, to support albums which are not available as tracks?  We can always revisit, but ideally, I would like to support all the common use cases in the first release.

It's late and I'm signing off for the evening, but will follow up on this tomorrow, as I want the PR to hit prod asap.  Thanks for working on this!

**Comment by RocketMan** [comment]
I've made some fixes and put up an initial attempt at an iconic play button instead of the hypertext text-based play.

Still playing with it and checking various edge cases.  If I don't find anything else, I'll merge the PR and go live with it, I hope maybe later today or Sunday.

**Comment by RocketMan** [comment]
Thanks Eric.  Your latest looks good in both kzsu and example.  There was one file I don't think you intended to commit, so I removed it (Playlist.php_ref).

So far, so good!  Unless you have more commits, I am thinking I will merge the PR in a few minutes, but as the prod database conversion could run a while, I'll deploy to prod during the AM hours local time.  I don't want to impact anyone's live use of zk during the day today.  So no worries, I can wait to merge until later as well.

**Comment by eric-gilbertson** [comment]
I pulled your latest change with the styled play button and I think that the large glyph is out of place in the track listing. Also, I would place the glyph after the track number. Here is what I used for this:

    * $link = $url == '' ? '' : "<A target='_blank' href='$url' >&#9658;$track</A>";

Given that  #9658 is the most commonly used play symbol it conveys the functionality and its smaller height provides better balance with the rest of the page.

**Comment by RocketMan** [comment]
> I pulled your latest change with the styled play button and I think that the large glyph is out of place in the track listing. Also, I would place the glyph after the track number. Here is what I used for this:
> 
> ```
> * $link = $url == '' ? '' : "<A target='_blank' href='$url' >&#9658;$track</A>";
> ```
> 
> Given that #9658 is the most commonly used play symbol it conveys the functionality and its smaller height provides better balance with the rest of the page.

I had tried the unicode character earlier, and it sort of got lost in the wall of text.  In fact, I had also tried it after the number, but it was even more lost.  Ended up with it in front.  I sort of like circle arrow, but could not find a unicode for it, so that's how we ended up with the glyph.

My doubt now is that it looks huge on some browsers.  Can you attach a screenshot?  For me, it is somewhat larger, but not huge.  See below.  Can you please attach what you see?

afbeelding

**Comment by RocketMan** [comment]
Ah, the other thing I didn't like about the arrow after the number is that the track titles no longer line up.  i.e., if the play arrow is present, the track title text is indented relative to others tracks above or below that are not playable.

**Comment by eric-gilbertson** [comment]
Attached is the screen shot you requested. The issues you site regarding the play gif can be fixed via spacing, eg. disambiguating it from the seq number and track name by adding additional left/right padding to the caret. OTOH, there is no way to achieve a balanced layout with the circle arrow, it is just too big for use in the track listing. If you do go forward with it please make sure that it is at least vertically centered with the track title.
track_list

**Comment by RocketMan** [comment]
added ability to play an album track from an associated URL

closes #166

**Pull request merged**
