### PR TITLE
52: convert track editor to use ajax when adding new tracks

### PR DESCRIPTION
**Pull request by eric-gilbertson**
- style editor widgets
   - insertTrack now returns 2 if the insertion was time stamped
   - don't call emitResponseHeader & emitBody if request is type 'appliction/json'
   - new track edit div and supporting javascript
   - AddTrack routine that adds track to PL and returns new row in html
   - server jquery.js locally (was from a CDN)

### CODE REVIEW

**Comment by RocketMan** [comment]
Hello Eric, there is a problem with the `js/jquery_2.0.3.min.js` file in the PR.  Can you please check?

**Comment by eric-gilbertson** [comment]
everything looks okay on my end. i did notice that it took a few hard resets in order to get the jquery import link to work due to the randomizer in the URL. did you try a hard reload? what problem are you seeing?

**Comment by RocketMan** [comment]
The file consists of a single line.  See:
https://github.com/eric-gilbertson/zookeeper/blob/ericg/52_restify_track_editor/js/jquery_2.0.3.min.js

**Comment by eric-gilbertson** [comment]
jquery issue has been resolved.

**Comment by RocketMan** [comment]
Thanks Eric!  It is working for me now.  A couple initial observations:

* There is a font/UI sizing issue, both in Firefox 60.8.0 esr and and Epiphany/WebKit 2.24.3.  It seems the font needs to be specified explicitly at some smaller size, or the fields need to be larger.  Screenshots below.

   At the same time, could we use flatter decoration for this, like in the library editor?  That way, the chrome of the input fields would consume minimal space.  Screenshot also below.

    Firefox:
Screenshot from 2019-08-07 17-34-44

    Epiphany/WebKit:
Screenshot from 2019-08-07 17-35-40

    Library Editor (re flat decoration):
Screenshot from 2019-08-07 17-53-44

* setFocus is not defined upon entry.  Expected:  setFocus to the Type field.

* Not a huge deal, but let's think about this one:  You have min tag size set to 5.  I figure this is a hack to avoid a REST call to get the track data whilst the DJ is keying in a longer tag, but this needs to be thought through in a way that does not preclude tags with 2, 3, or 4 digits.  For example, in my test database, the tags are all 2 in length, so I had to change this.  I realize shorter tags are an edge case, as it excludes 'only' 997 albums, but the playlist editor should allow for all albums.

* The local jquery file has a sourceMappingURL which is throwing warnings in my console, because the map file it references does not exist.

* This one I can fix, but I want you to be aware, for the future:  The REST URLs are referencing / rather than the current directory (e.g., `/?action=addTrack` rather than `?action=addTrack` and `/zkapi.php` rather than `zkapi.php`, which breaks installations where the installation lives in a subdirectory (as it does in my dev env).  Let's keep it directory agnostic.

Thanks again for your work on this!

**Comment by eric-gilbertson** [comment]
regarding the minimum ID length check, it originally started as a mechanism to suppress spurious ajax calls during debugging. the addition of the key click timeout has reduced the need for this. thus the question is whether to remove it completely or to make this a configurable value. any thoughts?

**Comment by RocketMan** [comment]
Re the tag length check, I'm ambivalent.  One thing you might consider is that the zkapi getTracksRq method returns property "code":  "100" if the tag is invalid, so you could just test that property and bail if it is 100.  This would avoid any state changes to the UI elements for spurious queries.

**Comment by eric-gilbertson** [comment]
Regarding the vertical spacing between form elements, if feel that the tight spacing used in the Library Editor makes it difficult to distinguish the inputs. I would also note that popular CSS libraries like bootstrap use generous inter-element spacing (too much IMO). Thus is would suggest keeping the track editor spacing as is and adjust to other forms similarly as they are upgraded.

**Comment by RocketMan** [comment]
That's fine and good to know; we want it to look and work the way people expect it to.  Any modernization you can bring to this is appreciated.

**Comment by RocketMan** [comment]
Thanks Eric.  The UI now seems fine in both browsers.

I am still getting the sourceMappingURL warning, and it is coming specifically from the locally served jquery js file:

Screenshot from 2019-08-12 10-16-45

The message is as it says: jquery contains a sourceMappingURL that points to a resource which does not resolve (we get a 404 if we try to follow it.)

This is only a warning, but ideally we would make it go away.  Can we just drop the sourceMappingURL from the jquery file, as there is no map file?

A couple more issues:

* If a track from Tag ID includes a single quote mark, the string is truncated at that point upon entry. This affects only Tag ID and not Manual:  (double quotes work fine in both cases)

before I hit Add Track:
Screenshot from 2019-08-12 10-14-35

after I hit Add Track, observe what happens with "Puol' Enkeli":
Screenshot from 2019-08-12 10-14-53

(The a b'c d/e entry is the previous Manual track, showing that case works as expected.)

* I am not seeing any way to key in custom track names in the Tag ID case.  Is this intentional?

All the other issues reported earlier have been resolved.

**Comment by RocketMan** [comment]
...also:

* Print View appears broken.  When I click on the link, I get a black page, the URL for which contains a suspicious looking entry for the 'playlist' query string parameter :  ...&playlist=Array&format=html...

**Comment by eric-gilbertson** [comment]
All issues fixed except the ability to add custom track name from a tag ID entry. Do we know if that feature is used much? Note, I never saw the jquery map 404 that you get so I still think it might be something on your end. Perhaps you can look into it if you still see it. I did upgrade to jquery 3.4.1 because I noticed that that is what the production deployment is serving.

**Comment by RocketMan** [comment]
Thanks Eric.  I am not seeing any new commits on `ericg/52_restify_track_editor`.  Can you please check to see that you pushed to origin?

**Comment by eric-gilbertson** [comment]
changes pushed.

**Comment by RocketMan** [comment]
Awesome, thanks Eric!  Everything looks good, and as well, the map warning went away (I will post more about that separately).

However, I notice two things.  Do you want me to go ahead and merge the PR as-is and then you fix after, or do you want to fix now?  They are:

* After doing a Tag ID and Add Track, the Track dropdown is still populated with the tracks from the last album  You can pick one of those and Add Track gets enabled, though the Tag field is blank and no album is selected.  Expected:  Track dropdown contents should be reset after Add Track.

* For compilation albums, the artist name is not displayed in the Track dropdown, only the track title.  Expected:  Track should show "nr. Artist - Track", analogous to the edit track function.

**Comment by RocketMan** [comment]
The source map functionality is offered only in Chrome and Firefox (if enabled), and is for developers basically to map minified JS back to the original source.  To use it, you have to deploy two additional files in addition to the minified one (the map and the original source).  I was getting the error, as I used Firefox with the feature enabled, and the other two files were missing.

Jquery stopped including the sourceMappingURL in the minified assets as of jQuery 1.11.0/2.1.0, which is why the warning has stopped.

I notice you now have two jquery files:  `jquery.min.js` and `jquery_3.4.1.min.js`.  Only the former seems to be referenced.

Given zk automatically decorates the resource name, there should be no browser caching should we update `jquery.min.js` in the future.  Would you be fine with deleting `jquery_3.4.1.min.js` and keeping only `jquery.min.js`?

**Comment by eric-gilbertson** [comment]
hey jim,

thanks for the diligent testing. glad you caught the single quote issue. why don't you wait on the merge and i will take care of the remaining issues.

**Comment by eric-gilbertson** [comment]
52: update track editing per review comments

   - include track artist when adding from a collection
   - store track titles in a global list , not in the option value
   - clear track picker before track fetch and after adding a track
   - fetch disk tracks on track picker gaining focus (if it is empty)
   - remove duplicate jquery (again)

**Comment by RocketMan** [comment]
Thanks Eric!  Remaining issues cleared; merging.

**Pull request merged**
